# Generated by Django 4.1.13 on 2023-12-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myphonepe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_status_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_tid', models.CharField(max_length=100)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentinitiate',
            name='name',
        ),
        migrations.AlterField(
            model_name='paymentinitiate',
            name='source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=20)),
                ('Second_Name', models.CharField(default='', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('Phone_Number', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
